export enum ActionTypes {
  // Authentication
  AUTHENTICATION_LOGIN = 'AUTHENTICATION_LOGIN',
  AUTHENTICATION_LOGIN_SUCCESS = 'AUTHENTICATION_LOGIN_SUCCESS',
  AUTHENTICATION_LOGIN_ERROR = 'AUTHENTICATION_LOGIN_ERROR',
  AUTHENTICATION_LOGOUT = 'AUTENTICATION_LOGOUT',
  AUTHENTICATION_GET_LOGIN_INFO = 'AUTHENTICATION_GET_LOGIN_INFO',
  AUTHENTICATION_GET_LOGIN_INFO_SUCCESS = 'AUTHENTICATION_GET_LOGIN_INFO_SUCCESS',
  AUTHENTICATION_GET_LOGIN_INFO_ERROR = 'AUTHENTICATION_GET_LOGIN_INFO_ERROR',

  // Game
  GAME_PLAYER_PICKED_CARD = 'GAME_PLAYER_PICKED_CARD',
  GAME_FELLOWPLAYER_PICKED_CARD = 'GAME_FELLOWPLAYER_PICKED_CARD',
  GAME_OPPONENT1_PICKED_CARD = 'GAME_OPPONENT1_PICKED_CARD',
  GAME_OPPONENT2_PICKED_CARD = 'GAME_OPPONENT2_PICKED_CARD'
};
