export enum ActionTypes {
  GAME_PLAYER_PICKED_CARD = 'GAME_PLAYER_PICKED_CARD',
  GAME_FELLOWPLAYER_PICKED_CARD = 'GAME_FELLOWPLAYER_PICKED_CARD',
  GAME_OPPONENT1_PICKED_CARD = 'GAME_OPPONENT1_PICKED_CARD',
  GAME_OPPONENT2_PICKED_CARD = 'GAME_OPPONENT2_PICKED_CARD'
};
